In [2]:
import pandas as pd
import numpy as np
import pandas_datareader as pdr
import os
import requests

In [2]:

# All Stock
ALL ={
    'name':'ALL',
    'portfolio':[
        '3008',	#光電業
        # '9910',	#其他
        # '2317',	#其他電子業
        '2454',	#半導體業
        '1326',	#塑膠工業
        '1101',	#水泥工業
        '2207',	#汽車工業
        '6505',	#油電燃氣業
        '2912',	#貿易百貨
        '4904',	#通信網路業
        '2882',	#金融保險業
        # '2002',	#鋼鐵工業
        '2327',	#電子零組件業
        # '2382',	#電腦及週邊設備業
        # '1216',	#食品工業
    ] 
}


# 0050 Y110Q3
TW0050 ={
    'name':'tech',
    'portfolio':[
        "1101", "1216", "1301", "1303", "1326", "1402", "1590", "2002", "2207", "2303", 
        "2308", "2317", "2324", "2327", "2330", "2357", "2379", "2382", "2395", #"2311",
        "2408", "2409", "2412", "2603", "2609", "2615", "2801", "2880", "2881", "2882", 
        "2884", "2885", "2886", "2887", "2891", "2892", "2912", "3008", "3034", "3045", 
        "4904", "4938", "5880", "6415", "6505", "8046", "8454", "9910"
    ] 
}
    
# Tech     
Tech ={
    'name':'tech',
    'portfolio':[
        '2317', # 鴻海
        '2409', # 友達
        '2330', # 台積電
        '2303', # 聯電
        '2301', # 光寶科
        '2308', # 台達電
        '2356', # 英業達
        '6770', # 力積電
        # '2353', # 宏碁
        # '3481', # 群創
        # '2312', # 金寶
        # '2324', # 仁寶
        # '2313', # 華通
        # '2327', # 國巨
    ]
}

# Financial
Fin ={
    'name':'fin',
    'portfolio':[
        '2891', # 中信金
        '2883', # 開發金
        '2885', # 元大金
        '2882', # 國泰金
        '2881', # 富邦金
        '2892', # 第一金
        '5880', # 合庫金
        '2884', # 玉山金
        '2887', # 台新金
        '2801', # 彰銀
        # '2890', # 永豐金
        # '2886', # 兆豐金
        # '2888', # 新光金
    ]
}


# experiments
Portfolio = ALL

# stock = '2330'
stock_period = ('2015/01/01', '2021/12/31')

In [4]:
stock_df=[]
for stock in Portfolio['portfolio']: 
    try:
        print(f'Start Download {stock}')
        df = pdr.DataReader(str(stock)+'.TW', 'yahoo', start=stock_period[0], end=stock_period[1])
        df[stock] = df['Close']
        df['date'] = df.index
        stock_df.append(df[['date',stock]])
    except:
        print(f'  {stock} Download Fail')
    
df = pd.concat(stock_df,axis=1).drop(columns='date')
df.index = df.index.to_series().apply(lambda x : str(x).replace('-','')[:8])
df.index.name = 'DateTime'
name = Portfolio['name']
df = df.dropna()
df.to_csv(os.path.join('data',f'{name}.csv'))
df

Start Download 3008
Start Download 2454
Start Download 1326
Start Download 1101
Start Download 2207
Start Download 6505
Start Download 2912
Start Download 4904
Start Download 2882
Start Download 2327

,3008,2454,1326,1101,2207,6505,2912,4904,2882,2327
DateTime,,,,,,,,,,
20100104,416.0,555.882324,66.893204,27.403181,76.500000,82.400002,76.000000,38.099998,46.747639,35.226406
20100105,408.5,556.862732,67.572815,28.361893,76.900002,83.000000,76.300003,38.000000,46.669067,35.226406
20100106,407.5,563.725464,72.135925,28.961086,76.699997,84.800003,76.400002,38.000000,47.454742,36.283199
20100107,401.0,550.000000,71.553398,28.401838,76.900002,85.500000,76.699997,37.250000,46.983337,35.367313
20100108,397.5,539.215698,69.902908,28.282000,77.300003,85.699997,77.000000,37.500000,47.454742,35.085503
...,...,...,...,...,...,...,...,...,...,...
20211224,2445.0,1120.000000,80.400002,47.900002,610.000000,96.800003,274.500000,63.900002,61.099998,473.000000
20211227,2450.0,1145.000000,80.699997,48.099998,615.000000,97.099998,274.000000,64.000000,61.299999,481.500000
20211228,2405.0,1175.000000,81.000000,48.150002,615.000000,97.000000,273.000000,64.300003,62.299999,478.000000
20211229,2405.0,1185.000000,81.000000,48.150002,620.000000,96.500000,273.500000,64.599998,63.000000,474.000000
20211230,2465.0,1190.000000,80.800003,48.000000,614.000000,95.900002,273.500000,64.599998,62.500000,479.500000

In [38]:
start_year = stock_period[0].split('/')[0]
end_year = stock_period[1].split('/')[0]

data = pd.read_csv(f'data/{name}.csv',index_col=0)
train = data.loc['20180101':'20201231']
train.to_csv(f'data/{name}_2018_2020.csv')
test = data.loc['20210101':'20211231']
test.to_csv(f'data/{name}_2021.csv')
test

,3008,2454,1326,1101,2207,6505,2912,4904,2882,2327
DateTime,,,,,,,,,,
20210104,3350.0,792.0,84.599998,43.200001,646.0,100.000000,268.5,61.200001,42.049999,520.0
20210105,3315.0,797.0,83.300003,43.099998,642.0,99.199997,272.0,61.400002,42.099998,528.0
20210106,3070.0,792.0,83.300003,42.950001,629.0,99.500000,271.0,61.299999,41.549999,513.0
20210107,3030.0,799.0,85.800003,42.849998,634.0,100.000000,271.0,61.400002,41.900002,529.0
20210108,3040.0,838.0,86.300003,42.950001,645.0,104.000000,273.0,62.000000,42.849998,572.0
...,...,...,...,...,...,...,...,...,...,...
20211224,2445.0,1120.0,80.400002,47.900002,610.0,96.800003,274.5,63.900002,61.099998,473.0
20211227,2450.0,1145.0,80.699997,48.099998,615.0,97.099998,274.0,64.000000,61.299999,481.5
20211228,2405.0,1175.0,81.000000,48.150002,615.0,97.000000,273.0,64.300003,62.299999,478.0
20211229,2405.0,1185.0,81.000000,48.150002,620.0,96.500000,273.5,64.599998,63.000000,474.0
20211230,2465.0,1190.0,80.800003,48.000000,614.0,95.900002,273.5,64.599998,62.500000,479.5

In [39]:
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {"dataset": "TaiwanStockInfo"}
translation = requests.get(url, params=parameter)
trans = translation.json()
df_info = pd.DataFrame(trans['data'])
drop_list = ['ETF', '上櫃指數股票型基金(ETF)','受益證券', '指數投資證券(ETN)', '其他', '所有證券 ', '存託憑證','Index', '大盤']
df_info = df_info[df_info['industry_category'].apply(lambda x : x not in drop_list)]
df_info['row'] = df_info.sort_values(['stock_id','industry_category'], ascending=[True,False]).groupby(['stock_id']).cumcount() + 1
df_info = df_info[df_info['row']==1]
df_info = df_info[['stock_id','stock_name','industry_category']]
df_info = df_info.rename(columns={'stock_id':'code','stock_name':'name','industry_category':'c_name'})
df_info = df_info[df_info['code'].apply(lambda x : x in Portfolio['portfolio'])]
df_info.to_csv(f'data/{name}_table.csv',index=False)
df_info

      code name  c_name
298   1101   台泥    水泥工業
354   1326   台化    塑膠工業
645   2207  和泰車    汽車工業
695   2327   國巨  電子零組件業
905   2454  聯發科    電子工業
1108  2882  國泰金    金融保險
1141  2912  統一超    貿易百貨
1166  3008  大立光    電子工業
1840  4904   遠傳    電子工業
2399  6505  台塑化   油電燃氣業

In [40]:

# df = pd.read_excel('C:/Users/yayay/Desktop/NativeCamp.xlsx',sheet_name=1)
# display(df.head())
# df_group = df.groupby(['stock','industry']).count().sort_values(by='name',ascending=False)
# df_group.to_csv('C:/Users/yayay/Desktop/history_0050.csv')

In [41]:

df = pd.read_csv('data\history_0050.csv')
# display(df[df['industry']=='鋼鐵工業'])
df_portfolio = df[df['name']>=9].sort_values(by='industry')
df_portfolio = df_portfolio.drop(columns = ['name','ratio'])
df_portfolio = df_portfolio.drop_duplicates(['industry'],keep='last')
df_portfolio

    stock  industry
13   3008       光電業
22   9910        其他
28   2317     其他電子業
21   2454      半導體業
31   1326      塑膠工業
0    1101      水泥工業
25   2207      汽車工業
20   6505     油電燃氣業
12   2912      貿易百貨
16   4904     通信網路業
4    2881     金融保險業
37   2002      鋼鐵工業
27   2308    電子零組件業
38   4938  電腦及週邊設備業
36   1216      食品工業

In [42]:
df = pd.read_csv('data/ALL.csv')
df.dropna().reset_index(drop=True)

,DateTime,3008,2454,1326,1101,2207,6505,2912,4904,2882,2327
0,20100104,416.0,555.882324,66.893204,27.403181,76.500000,82.400002,76.000000,38.099998,46.747639,35.226406
1,20100105,408.5,556.862732,67.572815,28.361893,76.900002,83.000000,76.300003,38.000000,46.669067,35.226406
2,20100106,407.5,563.725464,72.135925,28.961086,76.699997,84.800003,76.400002,38.000000,47.454742,36.283199
3,20100107,401.0,550.000000,71.553398,28.401838,76.900002,85.500000,76.699997,37.250000,46.983337,35.367313
4,20100108,397.5,539.215698,69.902908,28.282000,77.300003,85.699997,77.000000,37.500000,47.454742,35.085503
...,...,...,...,...,...,...,...,...,...,...,...
2939,20211224,2445.0,1120.000000,80.400002,47.900002,610.000000,96.800003,274.500000,63.900002,61.099998,473.000000
2940,20211227,2450.0,1145.000000,80.699997,48.099998,615.000000,97.099998,274.000000,64.000000,61.299999,481.500000
2941,20211228,2405.0,1175.000000,81.000000,48.150002,615.000000,97.000000,273.000000,64.300003,62.299999,478.000000
2942,20211229,2405.0,1185.000000,81.000000,48.150002,620.000000,96.500000,273.500000,64.599998,63.000000,474.000000
2943,20211230,2465.0,1190.000000,80.800003,48.000000,614.000000,95.900002,273.500000,64.599998,62.500000,479.500000

In [5]:
df = pd.read_csv("data/fin_2021.csv")
display(df)
display(df.iloc[5:])

,DateTime,2891,2883,2885,2882,2881,2892,5880,2884,2887,2801
0,20210104,19.549999,9.24,20.450001,42.049999,42.045452,20.891088,19.754902,23.890032,12.626431,17.623762
1,20210105,19.600000,9.24,20.549999,42.099998,42.136364,21.039602,19.901960,23.842911,12.626431,17.524752
2,20210106,19.549999,9.28,20.650000,41.549999,41.454544,20.792080,19.754902,23.748671,12.578604,17.425741
3,20210107,19.799999,9.29,21.000000,41.900002,42.000000,21.039602,19.754902,23.748671,12.578604,17.524752
4,20210108,20.000000,9.41,21.350000,42.849998,43.136364,21.287128,19.950979,24.031393,12.722086,17.772278
...,...,...,...,...,...,...,...,...,...,...,...
238,20211224,25.850000,16.85,25.000000,61.099998,75.199997,24.200001,25.049999,27.950001,18.750000,16.750000
239,20211227,25.799999,16.90,25.000000,61.299999,75.199997,24.250000,25.000000,27.950001,18.750000,16.799999
240,20211228,25.950001,17.10,25.049999,62.299999,75.900002,24.350000,25.350000,28.000000,18.900000,16.950001
241,20211229,26.100000,17.60,25.299999,63.000000,76.599998,24.549999,25.500000,28.049999,18.950001,17.049999
242,20211230,25.950001,17.50,25.299999,62.500000,76.300003,24.500000,25.450001,28.049999,18.950001,17.000000

,DateTime,2891,2883,2885,2882,2881,2892,5880,2884,2887,2801
5,20210111,19.950001,9.71,21.900000,42.599998,43.090908,21.287128,20.000000,24.031393,12.769913,17.772278
6,20210112,19.700001,9.47,21.250000,42.299999,43.409088,21.089108,19.705881,23.842911,12.626431,17.524752
7,20210113,19.850000,9.51,21.400000,42.400002,43.909088,21.039602,19.754902,23.842911,12.674259,17.772278
8,20210114,19.850000,9.46,21.200001,42.500000,44.045452,21.089108,19.803921,23.748671,12.722086,17.722773
9,20210115,19.700001,9.28,21.000000,41.799999,43.272728,20.841583,19.705881,23.560188,12.578604,17.524752
...,...,...,...,...,...,...,...,...,...,...,...
238,20211224,25.850000,16.85,25.000000,61.099998,75.199997,24.200001,25.049999,27.950001,18.750000,16.750000
239,20211227,25.799999,16.90,25.000000,61.299999,75.199997,24.250000,25.000000,27.950001,18.750000,16.799999
240,20211228,25.950001,17.10,25.049999,62.299999,75.900002,24.350000,25.350000,28.000000,18.900000,16.950001
241,20211229,26.100000,17.60,25.299999,63.000000,76.599998,24.549999,25.500000,28.049999,18.950001,17.049999
242,20211230,25.950001,17.50,25.299999,62.500000,76.300003,24.500000,25.450001,28.049999,18.950001,17.000000

In [3]:
from utils import get_data

stock_name = 'All'
stock_table = f"{stock_name}_table"
window = False
data = get_data(stock_name, stock_table)
data

array([[  27.40318108,   28.3618927 ,   28.96108627, ...,   48.15000153,
          48.15000153,   48.        ],
       [  66.89320374,   67.57281494,   72.13592529, ...,   81.        ,
          81.        ,   80.80000305],
       [  76.5       ,   76.90000153,   76.69999695, ...,  615.        ,
         620.        ,  614.        ],
       ...,
       [ 416.        ,  408.5       ,  407.5       , ..., 2405.        ,
        2405.        , 2465.        ],
       [  38.09999847,   38.        ,   38.        , ...,   64.30000305,
          64.59999847,   64.59999847],
       [  82.40000153,   83.        ,   84.80000305, ...,   97.        ,
          96.5       ,   95.90000153]])

In [81]:
print(data[:,0])
print(data[:,39])
print(data[:,40])
print(data[:,41])
# print(data[:,11])
# data[:,0:2].reshape(10,10)

[ 27.40318108  66.89320374  76.5         35.2264061  555.88232422
  46.7476387   76.         416.          38.09999847  82.40000153]
[ 23.7281189   72.62136078  68.19999695  35.79002762 521.56860352
  42.42642593  76.09999847 427.          37.90000153  82.        ]
[ 23.7281189   72.13592529  67.69999695  35.50821686 527.45098877
  42.74069595  74.90000153 438.          37.95000076  82.5       ]
[ 23.68817139  72.03883362  67.59999847  35.36731339 535.29412842
  41.71931839  76.09999847 434.          37.79999924  81.90000153]

In [83]:
print(data.shape)

cur_step = 40 
slide = 20
# print(data[:,cur_step-5:cur_step])

obs = []
if cur_step < slide:
    print(f'in slide cur_step:{cur_step} slide:{slide} range:{0,(slide-cur_step)}')
    # for i in range(0,(slide-cur_step)):
    for i in range(0,slide):
        obs.append(data[:,0])
    # print('loop add end')   
    for i in range(0,cur_step+1):
        print(i)
        obs.append(data[:,i])
    # obs.append(data[:,cur_step])
    obs = obs[-slide:]
    # print(obs)
else:
    print(f'out slide {cur_step} {slide}')
    for i in range((cur_step-slide),cur_step+1):
        obs.append(data[:,i])
    obs = obs[-slide:]
obs = np.array(obs)
# print(obs)
obs = np.reshape(obs, (1, obs.shape[0], obs.shape[1]))
print(f'obs shape ({obs.shape})')
obs

(10, 2944)
out slide 40 20
obs shape ((1, 20, 10))

array([[[ 23.60827827,  65.53398132,  69.30000305,  34.02870941,
         488.23529053,  41.64075089,  75.        , 413.        ,
          38.40000153,  78.69999695],
        [ 23.84795761,  65.43688965,  69.        ,  33.60599136,
         499.01959229,  41.8764534 ,  75.        , 426.        ,
          39.        ,  79.09999847],
        [ 23.92785072,  66.89320374,  67.59999847,  33.39463425,
         504.90194702,  41.79788589,  74.69999695, 430.        ,
          38.34999847,  78.80000305],
        [ 22.80935287,  66.01941681,  64.90000153,  31.35150146,
         500.9803772 ,  39.12659454,  72.59999847, 413.        ,
          37.20000076,  78.19999695],
        [ 22.60962105,  65.14562988,  63.40000153,  31.91512489,
         496.07843018,  39.67656708,  72.5       , 412.        ,
          37.29999924,  79.        ],
        [ 23.0090847 ,  65.72815704,  64.30000305,  31.91512489,
         501.96078491,  40.0694046 ,  72.5       , 409.        ,
          37.34999847,  79.40000153],
        [ 23.48843956,  66.01941681,  65.30000305,  32.54919815,
         507.84313965,  40.0694046 ,  72.5       , 414.        ,
          37.40000153,  78.80000305],
        [ 23.8080101 ,  67.76699066,  65.        ,  32.9719162 ,
         518.62744141,  41.79788589,  75.69999695, 419.        ,
          37.54999924,  81.69999695],
        [ 24.04768944,  69.90290833,  64.59999847,  32.9719162 ,
         523.52941895,  41.8764534 ,  75.09999847, 429.5       ,
          37.59999847,  82.09999847],
        [ 24.28736687,  68.73786163,  65.        ,  32.69010544,
         517.64703369,  41.16934586,  75.80000305, 421.        ,
          37.59999847,  82.        ],
        [ 23.48843956,  69.51456451,  65.        ,  31.77421951,
         497.05883789,  40.38367462,  75.59999847, 418.5       ,
          37.59999847,  80.        ],
        [ 23.64822578,  70.38835144,  65.5       ,  32.83101273,
         495.09805298,  40.61937332,  75.40000153, 413.5       ,
          38.20000076,  81.19999695],
        [ 24.04768944,  70.58252716,  65.5       ,  32.54919815,
         507.84313965,  41.24791336,  76.        , 423.        ,
          38.15000153,  81.19999695],
        [ 24.16752815,  70.29125977,  65.80000305,  32.69010544,
         505.88235474,  41.16934586,  76.09999847, 423.5       ,
          37.79999924,  81.59999847],
        [ 24.28736687,  70.58252716,  65.80000305,  32.9719162 ,
         514.70587158,  41.9550209 ,  76.09999847, 424.        ,
          37.70000076,  81.5       ],
        [ 24.00774384,  71.26213837,  65.5       ,  32.54919815,
         503.92156982,  41.32648087,  76.19999695, 421.5       ,
          37.79999924,  80.40000153],
        [ 23.92785072,  71.8446579 ,  65.69999695,  33.11282349,
         499.01959229,  42.03358841,  76.19999695, 421.5       ,
          38.15000153,  81.69999695],
        [ 23.7680645 ,  72.62136078,  65.90000153,  34.73323822,
         517.64703369,  42.34785843,  76.19999695, 429.        ,
          37.84999847,  81.69999695],
        [ 23.7281189 ,  72.62136078,  68.19999695,  35.79002762,
         521.56860352,  42.42642593,  76.09999847, 427.        ,
          37.90000153,  82.        ],
        [ 23.7281189 ,  72.13592529,  67.69999695,  35.50821686,
         527.45098877,  42.74069595,  74.90000153, 438.        ,
          37.95000076,  82.5       ]]])

In [7]:
model = 'lstm'
if model in ['conv1d', 'lstm']:
    print('go window')
else:    
    print('not')

go window

In [23]:
import gym
env = gym.make('CartPole-v0')

# Environment parameters
n_actions = env.action_space.n
n_states = env.observation_space.shape[0]
env.observation_space

c:\Users\yayay\.virtualenvs\DeepPortfolio_Trading-Fkpr0eim\lib\site-packages\gym\envs\registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)

Box(4,)