In [1]:
import pandas as pd
import numpy as np
import pandas_datareader as pdr
import os
import requests

In [5]:
# 0050 Y110Q3
TW0050 ={
    'name':'tech',
    'portfolio':[
        "1101", "1216", "1301", "1303", "1326", "1402", "1590", "2002", "2207", "2303", 
        "2308", "2317", "2324", "2327", "2330", "2357", "2379", "2382", "2395", #"2311",
        "2408", "2409", "2412", "2603", "2609", "2615", "2801", "2880", "2881", "2882", 
        "2884", "2885", "2886", "2887", "2891", "2892", "2912", "3008", "3034", "3045", 
        "4904", "4938", "5880", "6415", "6505", "8046", "8454", "9910"
    ] 
}
    
# Tech     
Tech ={
    'name':'tech',
    'portfolio':[
        '2317', # 鴻海
        '2409', # 友達
        '2330', # 台積電
        '2303', # 聯電
        '3481', # 群創
    ]
}

# experiments
Portfolio = Tech

# stock = '2330'
stock_period = ('2018/01/01', '2021/12/31')

In [8]:
stock_df=[]
for stock in Portfolio['portfolio']: 
    print(f'Start Download {stock}')
    df = pdr.DataReader(str(stock)+'.TW', 'yahoo', start=stock_period[0], end=stock_period[1])
    df[stock] = df['Close']
    df['date'] = df.index
    stock_df.append(df[['date',stock]])
    
df = pd.concat(stock_df,axis=1).drop(columns='date')
df.index = df.index.to_series().apply(lambda x : str(x).replace('-','')[:8])
name = Portfolio['name']
df.to_csv(os.path.join('data',f'{name}.csv'))

Start Download 2317
Start Download 2409
Start Download 2330
Start Download 2303
Start Download 3481

In [12]:
start_year = stock_period[0].split('/')[0]
end_year = stock_period[1].split('/')[0]

data = pd.read_csv(f'data/{name}.csv',index_col=0)
train = data.loc['20180101':'20201231']
train.to_csv(f'data/{name}_2018_2020.csv')
test = data.loc['20210101':'20211231']
test.to_csv(f'data/{name}_2021.csv')
test

                2317       2409   2330       2303       3481
Date
20210104   99.900002  14.200000  536.0  45.549999  14.350000
20210105  104.000000  14.000000  542.0  46.349998  14.000000
20210106  105.000000  13.500000  549.0  46.950001  13.300000
20210107  107.000000  13.800000  565.0  46.200001  13.550000
20210108  108.000000  13.900000  580.0  47.849998  13.350000
...              ...        ...    ...        ...        ...
20211224  104.000000  22.450001  604.0  64.300003  19.049999
20211227  104.500000  22.700001  606.0  64.300003  19.299999
20211228  105.500000  22.650000  615.0  64.699997  19.400000
20211229  105.000000  22.750000  616.0  65.000000  19.400000
20211230  104.000000  22.900000  615.0  65.000000  19.600000

[243 rows x 5 columns]

In [14]:
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {"dataset": "TaiwanStockInfo"}
translation = requests.get(url, params=parameter)
trans = translation.json()
df_info = pd.DataFrame(trans['data'])
drop_list = ['ETF', '上櫃指數股票型基金(ETF)','受益證券', '指數投資證券(ETN)', '其他', '所有證券 ', '存託憑證','Index', '大盤']
df_info = df_info[df_info['industry_category'].apply(lambda x : x not in drop_list)]
df_info['row'] = df_info.sort_values(['stock_id','industry_category'], ascending=[True,False]).groupby(['stock_id']).cumcount() + 1
df_info = df_info[df_info['row']==1]
df_info = df_info[['stock_id','stock_name','industry_category']]
df_info = df_info.rename(columns={'stock_id':'code','stock_name':'name','industry_category':'c_name'})
df_info = df_info[df_info['code'].apply(lambda x : x in Portfolio['portfolio'])]
df_info.to_csv(f'data/{name}_table.csv',index=False)
df_info

      code name c_name
667   2303   聯電   電子工業
685   2317   鴻海   電子工業
701   2330  台積電   電子工業
825   2409   友達   電子工業
1455  3481   群創   電子工業